DROP DATABASE IF EXISTS productdb;
CREATE DATABASE productdb;
USE productdb;

CREATE TABLE IF NOT EXISTS product(
    productId INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    sku VARCHAR(20) NOT NULL,
    name VARCHAR(50) NOT NULL,
    price DECIMAL(6,2) NOT NULL,
    categoryId INTEGER NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS furniture(
    furnitureId INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    height DECIMAL(4,2) NOT NULL,
    width DECIMAL(4,2) NOT NULL,
    length DECIMAL(4,2) NOT NULL,
    FOREIGN KEY(categoryId) REFERENCES product(categoryId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS book(
    bookId INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    weight DECIMAL(4,2) NOT NULL,
        categoryId INTEGER,
    FOREIGN KEY(categoryId) REFERENCES product(categoryId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS DVD(
    dvdId INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    size DECIMAL(6,2) NOT NULL,
    categoryId INTEGER,
    FOREIGN KEY(categoryId) REFERENCES product(categoryId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO product(sku, name, price, categoryId) VALUES
('TR120555', 'Chair',  40.00, 1),
('TR120556', 'Desk', 50.00, 1),
('TR120557', 'Bench', 60.00, 2);

INSERT INTO furniture(height, width, length) VALUES
(16.6, 17.4, 8.9),
(16.6, 17.4, 8.9);

INSERT INTO book(weight) VALUES
(17.3),
(95.5);

INSERT INTO DVD(size) VALUES(1024);